# Use Maven to build the project
FROM maven:3.8.5-openjdk-17-slim

# Copy the pom.xml file into the /app/ directory
COPY pom.xml /app/

# Copy the source code into the /app/src/ directory
COPY src /app/src/

# Set the working directory to the /app/ directory
WORKDIR /app/

ENTRYPOINT mvn test -Pdev