server:
  port: 80

spring:

  mvc:
    servlet:
      path: /

  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mymanagement?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: jhi40S8232amR #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)s
  tokenHead: Linck  #JWT负载中拿到开头

logging:
  level:
    com:
      linck:
        management:
          system:
            mapper: debug